/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travel.expense.calculator;

/**
 *
 * @author emapa
 */
public class Advice extends javax.swing.JFrame {

    /**
     * Creates new form Currency
     */
    public Advice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 153, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("Pack light with only essentials to maximize mobility and convenience.\n\nPlan your itinerary efficiently to make the most of your limited time.\n\nResearch local transportation options for seamless navigation between attractions.\n\nPrioritize must-see attractions and activities to avoid feeling overwhelmed.\n\nBook accommodations in advance to secure the best deals and locations.\n\nInvest in a reliable travel guide or map for easy reference while exploring.\n\nPack snacks and water to stay energized and hydrated throughout the day.\n\nDress comfortably and appropriately for the local climate and activities planned.\n\nUse technology wisely for navigation, translation, and capturing memories.\n\nStay vigilant with your belongings in crowded tourist areas to prevent theft.\n\nBe respectful of local customs, traditions, and etiquette during your visit.\n\nBudget wisely and keep track of your expenses to avoid overspending.\n\nAllow time for relaxation and spontaneous exploration to fully enjoy your surroundings.\n\nTake advantage of guided tours or local experts for immersive cultural experiences.\n\nStay flexible and open to unexpected opportunities or changes in plans.\n\nMake use of public spaces like parks or plazas for leisure and people-watching.\n\nTry local cuisine and street food for an authentic taste of the destination.\n\nTake breaks to rest and recharge, especially during full-day sightseeing.\n\nStay mindful of your environmental impact and dispose of waste responsibly.\n\nCapture memories through photos, but also take time to fully experience each moment without the lens.\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Short-term travel tips", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 153, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Plan your budget wisely and consider long-term accommodation options like rentals or house sitting.\n\nPack versatile clothing and essentials, focusing on durability and comfort.\n\nEmbrace slow travel to immerse yourself in local cultures and reduce travel fatigue.\n\nStay connected with loved ones through regular communication to combat homesickness.\n\nTake breaks when needed to prevent burnout and exhaustion.\n\nLearn basic phrases in the local language to facilitate communication and cultural integration.\n\nCreate a flexible itinerary to allow for spontaneous experiences and changes in plans.\n\nStay organized by keeping important documents secure and easily accessible.\n\nMaintain good health with regular exercise, balanced meals, and sufficient rest.\n\nEmbrace minimalism and avoid accumulating unnecessary belongings during your travels.\n\nStay aware of visa requirements and plan for necessary extensions or renewals.\n\nVolunteer or work remotely to enrich your travel experience and extend your stay in certain destinations.\n\nPractice responsible tourism by respecting local customs, traditions, and environments.\n\nKeep a journal or blog to document your experiences and reflect on your journey.\n\nStay safe by researching potential risks and staying informed about local laws and regulations.\n\nInvest in travel insurance to protect yourself against unexpected emergencies or setbacks.\n\nConnect with other travelers and locals through social media, forums, or meet-up groups.\n\nExplore off-the-beaten-path destinations to discover hidden gems and avoid crowds.\n\nTake time for self-care and relaxation to maintain mental and emotional well-being.\n\nBe open-minded, flexible, and adaptable to the challenges and rewards of long-term travel.");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Long-term travel tips", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Advice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Advice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Advice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Advice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Advice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
